language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_STATIC_ANALYSIS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_STATIC_ANALYSIS=0 # set to 1 to enable static analysis
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      pecl install ast
    fi

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      composer phan
    fi
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      cat analysis.txt
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

notifications:
  slack:
    -
      rooms:
        -
          secure: orUTrXiVOI5FaZl0504lqf2+hi8Kx4IxKfNP2jywr9T2ztpX1fjBZXgIg2Cc396TTjLI9tG0cqjTfzDROMVLD68ioTqtFe1Ydy+HCkSXWvMWYFrRs8mT1xU1km4qcLZ8QZUWJjMMAKCPnIFZnNy/W5ncvm0FwJK0PZU7ONS3JzNjk9UY/yeqDmpcaeUDlowAf/a6nE6LFztEsoppGOvWfKlxPAb7ztoPT2+q61IKyg6c2ZcGFtvhUsg+TQCKOJXc57HIjm1Zwzr8HQDvSCK+fZgqdWb4o6R3IJsL/IneaR5X5Ii3ZCTLvomuUHKJjqcrbAekW1NVfeTkXrMNVT+psxAE+pFa9JcIbflvE206iUfztQ4xIFQAJjuxU3g5ym/ddaJZelKgUNnOPJgjFOmpxfga32JEtLZ0plgHp/CG5lgCj5JxP74NQ2IuI/CXB4OEgpLRzKXiQev0KpaFjabmapfGDGnuhvbydtVGC6ampc/TdeOSsRZ6MpBqkTCms4QAMtT3HSlGP7CKOnirfHuybBfd2R1wvb9Zh8nzzKmUKc938Tn2Jm6vD0LOB4qmxUOluQ8VtNQAM9FUTV1t4x5KbXFzwpmj12px5bmfyhY2ZnbftnhgG6HWUvuEMs7ma6v/scHBaa35stmQ7lQDwTtg440E7WLq5df2rFEojY5yewk=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: tR+K2qm5ONBn3Tv95VGJNdVKPkn0RUUZMpSSnnwhAlkl2OyG5D8zcBYYU6eWLmXhkhb9bMTXUyYKD1e9cSK//MR7lEqoEnOr1GdKG3XRvK9ec6qJaItfL1jqUmYix99l6jU+FzlzW6s/km8xAfOIXecQNrgAntSDBT2IFYhUq8DvOrClofhY3ySbYwJrI6rtaSZ/Y3hwy5FZWGKE+o2NK8Nq3aeAuBI5+ufm4bfueADTEtn3Gf5ArOc9ishSTbZXkSFXEfcNYacyxQic3Fj2iGZQMpbFzJ0BUTFhOe0mns10HyUPH4umCNFwt7Ph8dcd6tMEZpwhlg95YFvMos02GefyIxkO/86jR2P14DfAht1TxIfFdeMsKRYhpwOxSVpmFPGS7VH1gni9nNR+SK2GfGNVuSpmx9nXrIFcpsBCcXLi4sR+vPtazxyO56pG2LeMuahRZ2G6mvv2mMqfTiwiHBfj4jHl8HfP2yiXz3FFMCsH3NIUa8UBYrMBPqMbsuZACciH6JWKS+P0PC7jq9AOc4n8fp8pWbn6PVnkY2U9LxeqVr2hvbFmj+YCyNG6X/0kZiw66X0hDYiK2cXp1peQxrirEGKsDoFpdwTnaJMAxlGKVKjxlAb6+EobhVXA9OaUkgtROnrBLp05V/6XXWcIC+lPdcOkxTKGlykMdFZ472s=
      on_success: never
      on_failure: always
      on_pull_requests: false
